# Generated by Django 3.2.7 on 2021-09-12 10:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('about', 'about'), ('Sercvices', 'Sercvices'), ('Slider', 'Slider'), ('Welcome', 'Welcome'), ('Major Services', 'Major Services'), ('Vision', 'Vision'), ('Mission', 'Mission')], max_length=255)),
                ('image', models.ImageField(default='', upload_to='')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Body')),
                ('addedon', models.DateField(auto_now=True)),
            ],
        ),
    ]
