# Generated by Django 3.1.1 on 2021-09-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_content_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('parent', models.CharField(max_length=250)),
                ('age', models.CharField(max_length=250)),
                ('dateofbirth', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('refferedyou', models.CharField(max_length=250)),
                ('hereabout', models.CharField(max_length=250)),
                ('emergencyname', models.CharField(max_length=250)),
                ('emergencyphone', models.CharField(max_length=250)),
                ('emergencyrelationship', models.CharField(max_length=250)),
                ('allergies', models.CharField(max_length=250)),
                ('currentmedication', models.CharField(max_length=250)),
                ('describeproblem', models.CharField(max_length=250)),
                ('interestedin', models.CharField(max_length=250)),
            ],
        ),
    ]
